noun = input ("Enter a noun")
print (noun)
wacky_state = input ("Enter a wacky state")
verb = input ("Enter a verb")
noun2 = input ("Enter a noun")
noun3 = input ("Enter a noun")
peoples_name = input ("Enter a person's name")
verb2 = input ("Enter a verb")
noun4 = input ("Enter a noun")
verb3 = input ("Enter a verb")
noun5 = input ("Enter a noun")
part_of_the_body = input ("Part of the body")
print("A", noun, "in", wacky_state, "was arrested this morning after he", verb, "a ", noun2, "in front of", noun3. peoples_name, "had a history of", verb2 "but no one-not even his", noun4 "-ever imagined he'd", verb3 "with a", noun5 "stuck in his", part_of_the_body.)